### ISSUE TITLE
Checkerboarding system missing inputs (clearly not on all computers)

### ISSUE THREAD

**Issue by blank3times** [BalintCsala/Minificent#1]
Occurs on 1.19.2 Vanilla with no other resource packs (Fabulous graphics), screen resolution matches settings inputted to shader editor

Upon loading in a world there's a series of errors:

> OpenGL debug message: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_LINK error has been generated. GLSL link failed for program 33, "": Uniform "OutSize" has different type across different shaders.
> '
> 
> Error encountered when linking program containing VS screenquad and FS de_checkerboard. Log output:

(Which is followed by warnings alternating with another message which is directly below)

> OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3891749976) glGetUniformLocation- program 33, "" is not linked'

(The above alternates with the following:)

> Uniform "OutSize" has different type across different shaders.
> Shader de_checkerboard could not find sampler named DiffuseSampler in the specified shader program.
> Shader de_checkerboard could not find sampler named DiffuseDepthSampler in the specified shader program.
> Shader de_checkerboard could not find uniform named ProjMat in the specified shader program.
> Shader de_checkerboard could not find uniform named OutSize in the specified shader program.
> Shader shadows could not find sampler named DataDepthSampler in the specified shader program.

(After multiple repetitions of the errors above it switches to just one error message repeating across multiple milliseconds:)
> OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error'

The result is that only the clouds, gui, and item-in-hand render, with the rest being black. Maybe the warnings are helpful if you care?

Warnings stop once you exit the world.

**Comment by blank3times** [comment]
Do you know of any sorts of intended hardware limitations for this pack that aren't noted in readme?

**Comment by BalintCsala** [comment]
I fixed the issue the error messages contained, if you stil have the problem please just post the full latest.log, not just small parts from it.

**Comment by blank3times** [comment]
This works, thank you! The log was all the parts but repeated thousands of times, so you fixed it.

Very cool to play around with.
